import type { AmbiguityLexicon } from "../types.js";

// テスト計画書レビュー（review_test_plan）専用の曖昧語・非測定表現の語彙集。
// 語彙・理由文・改善提案文はすべて自作の日本語文であり、JSTQB等の外部文献の逐語転載ではない。
// src/testBasisAnalysis.ts の DEFAULT_AMBIGUOUS_TERMS とは独立したデータであり、共有・共通化はしない。
export const testPlanAmbiguityLexicon: AmbiguityLexicon = {
  name: "テスト計画書レビュー用曖昧語レキシコン（自作整理）",
  note:
    "開始・終了基準や合否判定基準など客観性が求められる章で、測定できない・範囲が閉じない・努力目標にとどまる表現を機械的に検出するための語彙集。特定の外部手法・文献の逐語転載ではない。",
  terms: [
    {
      id: "AMB-01",
      term: "適切に",
      category: "non-measurable",
      reason: "何をもって適切とするかの判定基準が示されておらず、読み手ごとに解釈が分かれる。",
      suggestion: "判定に用いる指標と閾値を明示する（例:「重大度Aの未解決不具合が0件」）。",
    },
    {
      id: "AMB-02",
      term: "適切な",
      category: "non-measurable",
      reason: "「適切な」が修飾する対象の合否を判定する具体的な基準が書かれていない。",
      suggestion: "対象を満たす条件を数値・状態で具体的に書き下す。",
    },
    {
      id: "AMB-03",
      term: "十分に",
      category: "non-measurable",
      reason: "どこまで実施すれば十分とみなすかの量的な線引きがない。",
      suggestion: "達成率や件数など、十分性を判定できる数値基準を示す。",
    },
    {
      id: "AMB-04",
      term: "十分な",
      category: "non-measurable",
      reason: "十分性の判定に用いる基準（量・網羅率等）が明記されていない。",
      suggestion: "十分と判断する具体的な数値・条件を追記する。",
    },
    {
      id: "AMB-05",
      term: "できる限り",
      category: "non-measurable",
      reason: "努力の程度を表すのみで、達成すべき最終ラインが読み取れない。",
      suggestion: "達成すべき最小ラインまたは目標値を数値で明記する。",
    },
    {
      id: "AMB-06",
      term: "可能な限り",
      category: "non-measurable",
      reason: "実施範囲の下限・上限が定まらず、実施漏れの検出ができない。",
      suggestion: "実施すべき範囲を条件で列挙し、対象外の判断基準も明記する。",
    },
    {
      id: "AMB-07",
      term: "なるべく",
      category: "non-measurable",
      reason: "努力目標の表現であり、実施の要否を機械的に判定できない。",
      suggestion: "実施の要否を条件分岐として明記する。",
    },
    {
      id: "AMB-08",
      term: "速やかに",
      category: "non-measurable",
      reason: "対応までに許容される時間の基準が示されていない。",
      suggestion: "許容時間（例:「検出から1営業日以内」）を数値で明示する。",
    },
    {
      id: "AMB-09",
      term: "定期的に",
      category: "non-measurable",
      reason: "周期の長さが特定できず、実施漏れの判定ができない。",
      suggestion: "周期（例:「毎週月曜日」「1スプリントごと」）を明示する。",
    },
    {
      id: "AMB-10",
      term: "ある程度",
      category: "non-measurable",
      reason: "程度を表す量的な線引きがなく、判定者によって解釈が変わる。",
      suggestion: "許容範囲・目標値を数値で示す。",
    },
    {
      id: "AMB-11",
      term: "概ね",
      category: "non-measurable",
      reason: "許容される乖離幅が示されておらず、合否判定にばらつきが出る。",
      suggestion: "許容誤差・達成率のしきい値を明記する。",
    },
    {
      id: "AMB-12",
      term: "柔軟に",
      category: "non-measurable",
      reason: "対応の裁量幅が示されておらず、実施基準として機能しない。",
      suggestion: "裁量を認める条件と、その範囲を具体的に列挙する。",
    },
    {
      id: "AMB-13",
      term: "等",
      pattern: "(?<![同均平対不])等(?!し|価|級|分|号|々)",
      category: "ambiguous",
      reason: "列挙の範囲が閉じておらず、対象に何が含まれるかが読み手に委ねられる。",
      suggestion: "対象を列挙し尽くすか、含まれる範囲の判定基準を明記する。",
    },
    {
      id: "AMB-14",
      term: "など",
      category: "ambiguous",
      reason: "列挙の範囲が閉じておらず、対象に何が含まれるかが読み手に委ねられる。",
      suggestion: "対象を列挙し尽くすか、含まれる範囲の判定基準を明記する。",
    },
    {
      id: "AMB-15",
      term: "その他",
      category: "ambiguous",
      reason: "「その他」が指す範囲が定義されておらず、対象漏れの判断ができない。",
      suggestion: "対象を具体的に列挙するか、含まれない条件を明記する。",
    },
    {
      id: "AMB-16",
      term: "必要に応じて",
      category: "ambiguous",
      reason: "実施の要否を判断する条件が示されておらず、恣意的な運用になりやすい。",
      suggestion: "実施が必要となる条件を具体的に列挙する。",
    },
    {
      id: "AMB-17",
      term: "場合によっては",
      category: "ambiguous",
      reason: "どの場合に該当するかの条件が示されていない。",
      suggestion: "該当する条件を列挙し、それ以外は対象外であることを明記する。",
    },
    {
      id: "AMB-18",
      term: "適宜",
      category: "ambiguous",
      reason: "実施のタイミング・方法が読み手の裁量に委ねられている。",
      suggestion: "実施のタイミングと方法を具体的に定める。",
    },
    {
      id: "AMB-19",
      term: "原則として",
      category: "ambiguous",
      reason: "原則から外れる例外の条件が示されておらず、適用範囲が閉じない。",
      suggestion: "原則と、例外が認められる条件の両方を明記する。",
    },
    {
      id: "AMB-20",
      term: "基本的に",
      category: "ambiguous",
      reason: "例外の扱いが明記されておらず、適用範囲が曖昧になる。",
      suggestion: "基本方針と例外条件を分けて明記する。",
    },
    {
      id: "AMB-21",
      term: "若干",
      category: "ambiguous",
      reason: "量の程度を表す具体的な数値がなく、許容範囲が判定できない。",
      suggestion: "許容される数値範囲を明記する。",
    },
    {
      id: "AMB-22",
      term: "望ましい",
      category: "weak-requirement",
      reason: "実施が努力目標にとどまり、必須か任意かが判定できない。",
      suggestion: "必須・任意のいずれかを明示し、必須なら達成基準も併記する。",
    },
    {
      id: "AMB-23",
      term: "推奨する",
      category: "weak-requirement",
      reason: "推奨にとどまり、未実施の場合に基準を満たさないと判定できるかが不明。",
      suggestion: "必須事項として扱うか任意事項として扱うかを明記する。",
    },
    {
      id: "AMB-24",
      term: "考慮する",
      category: "weak-requirement",
      reason: "考慮した結果として何を満たすべきかが定まっていない。",
      suggestion: "考慮した結果として満たすべき条件・成果物を明記する。",
    },
    {
      id: "AMB-25",
      term: "検討する",
      category: "weak-requirement",
      reason: "検討の期限・結論の反映先が示されておらず、実施状況を追跡できない。",
      suggestion: "検討の期限と、結論を反映する場所・基準を明記する。",
    },
    {
      id: "AMB-26",
      term: "努める",
      category: "weak-requirement",
      reason: "努力目標の表現であり、達成できたかどうかを判定する基準がない。",
      suggestion: "達成すべき具体的な基準を明記し、必須事項として扱う。",
    },
    {
      id: "AMB-27",
      term: "可能であれば",
      category: "weak-requirement",
      reason: "実施の可否を左右する条件が示されておらず、任意実施の判断が恣意的になる。",
      suggestion: "実施可否を判断する具体的な条件を明記する。",
    },
  ],
  prioritySections: [
    { no: "6.1", titleJa: "開始・終了基準", severity: "high" },
    { no: "6.2", titleJa: "合否判定基準", severity: "high" },
    { no: "6.3", titleJa: "完了基準", severity: "high" },
    { no: "7", titleJa: "中断・再開基準", severity: "high" },
    { no: "6.4", titleJa: "インシデント判定基準", severity: "medium" },
    { no: "6.5", titleJa: "質問事項重要度基準", severity: "medium" },
    { no: "10.1", titleJa: "テスト環境要件", severity: "medium" },
    { no: "10.2", titleJa: "テストデータ要件", severity: "medium" },
  ],
};
