import type { ExecutionOrderAnalysisCriteria } from "../types.js";

// analyze_execution_order の判定区分カタログ。本プロジェクト独自の判定区分。
export const executionOrderAnalysisCriteria: ExecutionOrderAnalysisCriteria = {
  name: "テスト実行順序・依存関係分析 判定区分カタログ",
  summary:
    "テストコンテナ(またはスイート／ケース)の実行順序・依存関係・所要時間・必要リソースを、宣言と実体(母集団・" +
    "産出成果物・アーキテクチャ母集団・SLO・合格基準)の双方向照合で点検するための判定区分。",
  categories: [
    {
      id: "EOC-01",
      nameJa: "ノードIDの重複",
      severity: "high",
      definition: "nodes[].id が重複している。",
      recommendedAction: "ノードIDを一意になるよう修正すること。",
    },
    {
      id: "EOC-02",
      nameJa: "依存先の母集団外参照",
      severity: "high",
      definition: "dependsOn[].fromId が nodes のいずれにも存在しない。",
      recommendedAction: "参照先IDの綴りを確認し、母集団に宣言済みのIDへ修正するか、当該ノードを追加すること。",
    },
    {
      id: "EOC-03",
      nameJa: "自己依存",
      severity: "high",
      definition: "dependsOn[].fromId が自ノードIDを指している。",
      recommendedAction: "自己参照の依存を削除すること。",
    },
    {
      id: "EOC-04",
      nameJa: "循環依存",
      severity: "high",
      definition: "トポロジカルソートが完了せず残余ノードがある。残余ノードIDと代表閉路を列挙する。",
      recommendedAction: "循環している依存の一部を解消し、実行順序が一意に決まる有向非巡回グラフにすること。",
    },
    {
      id: "EOC-05",
      nameJa: "依存関係の未宣言",
      severity: "high",
      definition: "dependsOn が undefined である(空配列による「依存なし」の明示は正常)。",
      recommendedAction: "依存が無いなら空配列で明示し、依存があるなら dependsOn に宣言すること。",
    },
    {
      id: "EOC-06",
      nameJa: "依存根拠の未記入",
      severity: "medium",
      definition: "dependsOn[].reason が未指定または空白のみである。",
      recommendedAction: "なぜその先行ノードに依存するのか reason に明記すること。",
    },
    {
      id: "EOC-07",
      nameJa: "依存根拠の実体不一致",
      severity: "high",
      definition:
        "basisKind:\"artifact\" なのに basisRef が先行ノードの producedArtifactIds に無い、または " +
        "basisKind:\"resource\" なのに resources[].id に無い、または basisKind:\"data\" なのに dataItemIds に無い。",
      recommendedAction: "宣言した根拠の実体(成果物・リソース・データ項目)が実在するよう、母集団または basisRef を修正すること。",
    },
    {
      id: "EOC-08",
      nameJa: "依存の重複宣言",
      severity: "info",
      definition: "同一 fromId → nodeId の辺が2件以上宣言されている。",
      recommendedAction: "重複した依存宣言を1本に統合すること。",
    },
    {
      id: "EOC-09",
      nameJa: "所要時間の未申告",
      severity: "medium",
      definition: "durationHours が未指定であり、クリティカルパス・競合検出の分母が縮む。",
      recommendedAction: "見積もりの所要時間(時間単位)を申告すること。",
    },
    {
      id: "EOC-10",
      nameJa: "必要リソースの未宣言",
      severity: "medium",
      definition: "requiredResources が undefined である(空配列は正常)。",
      recommendedAction: "必要なリソースが無いなら空配列で明示し、あるなら requiredResources に宣言すること。",
    },
    {
      id: "EOC-11",
      nameJa: "必要リソースの母集団外参照",
      severity: "high",
      definition: "requiredResources[].resourceId が resources[].id に無い。",
      recommendedAction: "参照先のリソースIDを確認し、宣言済みの resources へ修正するか、当該リソースを追加すること。",
    },
    {
      id: "EOC-12",
      nameJa: "リソース競合",
      severity: "high",
      definition: "最早開始スケジュール上で同一リソースの同時要求量が capacity を超える。",
      recommendedAction: "実行順序をずらすか、リソースの capacity を増やすか、代替リソースの割当を検討すること。",
    },
    {
      id: "EOC-13",
      nameJa: "並列度上限の超過",
      severity: "medium",
      definition: "maxParallelism 指定時、同時実行ノード数がそれを超える区間がある。",
      recommendedAction: "並列度上限を超える区間の実行順序をずらすか、上限自体の妥当性を再確認すること。",
    },
    {
      id: "EOC-14",
      nameJa: "宣言リソースの未使用",
      severity: "medium",
      definition: "resources に宣言されたがどのノードからも要求されていない。",
      recommendedAction: "使われていないリソース宣言を削除するか、対応するノードの requiredResources に追加すること。",
    },
    {
      id: "EOC-15",
      nameJa: "孤立ノード",
      severity: "info",
      definition: "先行も後続も持たないノード(実行計画からの取りこぼし候補)。",
      recommendedAction: "本当に他ノードと依存関係が無いか、取りこぼしが無いかを確認すること。",
    },
    {
      id: "EOC-16",
      nameJa: "クリティカルパス宣言の不一致",
      severity: "high",
      definition: "claimedCriticalPathNodeIds が算出値と不一致、または算出不能で裏付けられない。",
      recommendedAction: "算出根拠(依存関係・所要時間)を確認し、宣言値を算出値に合わせるか、算出可能な状態まで入力を補うこと。",
    },
    {
      id: "EOC-17",
      nameJa: "総所要時間宣言の不一致",
      severity: "high",
      definition: "claimedTotalDurationHours が算出値と不一致、または算出不能で裏付けられない。",
      recommendedAction: "所要時間の申告を補うか、宣言値を算出値に合わせること。",
    },
    {
      id: "EOC-18",
      nameJa: "アーキテクチャ母集団の未計画コンテナ",
      severity: "high",
      definition: "architectureContainerIds にあるが nodes に無い。",
      recommendedAction: "実行計画に含まれていないコンテナを nodes へ追加するか、対象外とする理由を明記すること。",
    },
    {
      id: "EOC-19",
      nameJa: "アーキテクチャ母集団外のノード",
      severity: "medium",
      definition: "nodes[].id が architectureContainerIds に無い(同項目指定時のみ判定)。",
      recommendedAction: "アーキテクチャ側のコンテナ母集団と実行計画のノードの対応関係を確認すること。",
    },
    {
      id: "EOC-20",
      nameJa: "合格基準の測定不能",
      severity: "high",
      definition: "exitCriteria[] が sloIds を1件も持たず、かつ statement に数値を含まない。",
      recommendedAction: "測定可能な数値基準を statement に含めるか、対応する SLO を sloIds で参照すること。",
    },
    {
      id: "EOC-21",
      nameJa: "SLO参照の実体不一致",
      severity: "high",
      definition:
        "sloIds が slos[].id に無い、またはどの exitCriteria からも参照されない slo がある(双方向)。",
      recommendedAction: "未定義のSLO参照を修正するか、宣言したSLOがいずれかの合格基準から参照されるようにすること。",
    },
    {
      id: "EOC-22",
      nameJa: "モニタリング計画の未宣言",
      severity: "medium",
      definition: "monitoringCheckpoints が未指定または0件である。",
      recommendedAction: "テスト実施期間中にレビュー・進捗確認を行うタイミングを monitoringCheckpoints に宣言すること。",
    },
    {
      id: "EOC-23",
      nameJa: "モニタリング時点・参照の範囲外",
      severity: "high",
      definition: "atHour が [0, totalDurationHours] の外、または afterNodeIds が母集団外である。",
      recommendedAction: "モニタリング時点・参照ノードを実行計画の範囲内に収まるよう修正すること。",
    },
    {
      id: "EOC-24",
      nameJa: "モニタリング指標の未接続",
      severity: "medium",
      definition: "チェックポイントが sloIds も exitCriterionIds も持たない。",
      recommendedAction: "そのチェックポイントで何を確認するのか、SLOまたは合格基準への参照を追加すること。",
    },
    {
      id: "EOC-25",
      nameJa: "計画被覆率の宣言不一致",
      severity: "high",
      definition: "claimedPlannedContainerCoveragePercent が算出値と不一致、または算出不能。",
      recommendedAction: "算出根拠(分母・分子)を確認し、宣言値を算出値に合わせるか、算出可能な状態まで入力を補うこと。",
    },
    {
      id: "EOC-26",
      nameJa: "ノード件数の上限超過",
      severity: "info",
      definition: "nodes.length > maxNodes。以降の算出を打ち切った。",
      recommendedAction: "対象を絞り込むか、必要であれば maxNodes を明示的に引き上げること。",
    },
    {
      id: "EOC-27",
      nameJa: "スケジュール未算出",
      severity: "info",
      definition: "durationHours の申告が1件も無い等でクリティカルパス・競合検出が不能である。",
      recommendedAction: "少なくとも一部のノードについて durationHours を申告すること。",
    },
  ],
  notes: [
    "本検査は渡されたノード母集団に対してのみ成立し、渡していない作業の取りこぼしは検出できない。",
    "所要時間・リソースは設計時の見積もり値であり実測値の代替にしない。一部未申告の場合、総所要時間は下限値として扱う。",
    "リソース競合は最早開始スケジュール(各ノードを ES で開始する前提)の重なりで判定する。実際の実行計画で意図的にずらす場合は本ツールの対象外。",
    "所要時間0時間(またはduration未申告)のノードは区間長ゼロとして競合判定から除外する。",
    "依存関係は「実行順序の制約」であり、SUT内部の処理順序・タイミングのテスト(技法カタログ TTK-10)とは別物。技法カタログの決定的カウント可否は本ツールでは変更しない。",
  ],
};
