import type { RegressionSelectionAnalysisCriteria } from "../types.js";

// select_regression_suite の判定区分カタログ。本プロジェクト独自の判定区分。
export const regressionSelectionAnalysisCriteria: RegressionSelectionAnalysisCriteria = {
  name: "リグレッションスイート選択 判定区分カタログ",
  summary:
    "テスト条件・テストケースの母集団に対する選択(残す/落とす)判定を、宣言と実体(母集団・変更差分区分・前バージョンスイート・" +
    "テストサイズ・実行時間)の双方向照合で点検するための判定区分。",
  categories: [
    {
      id: "RSC-01",
      nameJa: "選択判定の母集団外参照",
      severity: "high",
      definition: "selections[].itemId が testConditions / testCases のいずれの母集団にも存在しない。",
      recommendedAction: "参照先IDの綴りを確認し、母集団に宣言済みのIDへ修正するか、当該項目を母集団へ追加すること。",
    },
    {
      id: "RSC-02",
      nameJa: "選択判定の重複・矛盾",
      severity: "high",
      definition: "同一項目に対する選択判定が複数宣言されている、または include/exclude が矛盾して宣言されている。",
      recommendedAction: "項目ごとに選択判定を1件に統一し、最新の判断のみを残すこと。",
    },
    {
      id: "RSC-03",
      nameJa: "選択理由の未記入",
      severity: "high",
      definition: "decision に対する reason が未指定、または空白のみで記録されている。",
      recommendedAction: "なぜ残す/落とすのかを reason に明記すること。",
    },
    {
      id: "RSC-04",
      nameJa: "高リスク項目の非選択",
      severity: "high",
      definition:
        "riskScore が highRiskMinScore 以上、または priority が「高」の項目が非選択(exclude)になっている。",
      recommendedAction: "本当に落としてよいか関係者と再確認し、残すか、除外する場合は根拠をreasonに明記すること。",
    },
    {
      id: "RSC-05",
      nameJa: "選択・非選択の未決定",
      severity: "high",
      definition: "母集団に存在するが selections のいずれにも現れず、選択・非選択が決まっていない。",
      recommendedAction: "全ての母集団項目について選択・非選択のいずれかを明示的に判定すること。",
    },
    {
      id: "RSC-06",
      nameJa: "変更差分区分の未宣言",
      severity: "high",
      definition: "テスト条件に changeCategory(RA-CHANGE 4区分)が宣言されておらず、変更差分区分に紐づかない。",
      recommendedAction: "new / modified / existing-impacted / existing-unaffected のいずれかを宣言すること。",
    },
    {
      id: "RSC-07",
      nameJa: "影響を受けない項目の選択",
      severity: "medium",
      definition: "existing-unaffected(既存・影響なし)の項目が選択(include)されている。",
      recommendedAction: "スイート肥大の候補であるため、本当に残す必要があるかを再確認すること。",
    },
    {
      id: "RSC-08",
      nameJa: "影響範囲条件の非選択・未決定",
      severity: "high",
      definition: "changeCategory が new / modified / existing-impacted の条件が非選択、または未決定である。",
      recommendedAction: "影響範囲に含まれる条件は原則として選択対象とし、除外する場合は明確な根拠を残すこと。",
    },
    {
      id: "RSC-09",
      nameJa: "削除理由の未記入",
      severity: "high",
      definition: "前バージョンのスイートから削除された項目に、removalReasons の記入が無い。",
      recommendedAction: "削除した項目それぞれについて、削除理由を removalReasons に記入すること。",
    },
    {
      id: "RSC-10",
      nameJa: "削除されていない項目への削除理由宣言",
      severity: "high",
      definition: "実際には削除されていない項目(現行スイートに残っている、または前バージョンに存在しない)に removalReasons が宣言されている。",
      recommendedAction: "宣言と実体が一致するよう、対象項目IDまたは削除理由の宣言を見直すこと。",
    },
    {
      id: "RSC-11",
      nameJa: "前バージョンスイートの母集団外参照",
      severity: "medium",
      definition: "previousSuite.items に、現在の母集団(testConditions / testCases)に存在しない項目が含まれている。",
      recommendedAction: "前バージョンのID体系と現行の母集団IDの対応を確認し、必要なら母集団側へ追加すること。",
    },
    {
      id: "RSC-12",
      nameJa: "ラージサイズ偏重",
      severity: "medium",
      definition: "選択したスイートのラージ構成比が testSizeClassificationCriteria の推奨構成比上限を超えている。",
      recommendedAction: "ラージテストの一部をミディアム/スモールへ分解できないか検討すること。",
    },
    {
      id: "RSC-13",
      nameJa: "推定実行時間の予算超過",
      severity: "medium",
      definition: "選択したスイートの推定合計実行時間が executionTimeBudgetSeconds を超えている。",
      recommendedAction: "実行時間予算内に収まるよう選択を見直すか、予算の妥当性を再確認すること。",
    },
    {
      id: "RSC-14",
      nameJa: "選択項目のサイズ判定入力欠落",
      severity: "medium",
      definition: "選択した case に外部依存(externalDependencyIds)・実行時間(estimatedDurationSeconds)のいずれの申告もなく、サイズ分布・推定実行時間の分母が縮んでいる。",
      recommendedAction: "外部依存の該当軸(無依存なら空配列)か想定実行時間(秒)を申告すること。",
    },
    {
      id: "RSC-15",
      nameJa: "影響範囲被覆率の宣言不一致",
      severity: "high",
      definition: "claimedImpactScopeCoveragePercent が算出値と一致しない、または算出不能(coverageBasis=unavailable)で裏付けられない。",
      recommendedAction: "算出根拠(分母・分子の元になる母集団・実体)を確認し、宣言値を算出値に合わせるか、算出可能な状態まで入力を補うこと。",
    },
    {
      id: "RSC-16",
      nameJa: "選択基準IDの未宣言参照",
      severity: "high",
      definition: "selections[].criterionIds が selectionCriteria[].id に存在しない基準IDを参照している。",
      recommendedAction: "参照先の基準IDを確認し、宣言済みの selectionCriteria へ修正するか、当該基準を追加すること。",
    },
    {
      id: "RSC-17",
      nameJa: "選択条件に対応するケース欠落",
      severity: "high",
      definition: "選択(include)した条件に対応するテストケースが1件も存在しない(testCases 指定時のみ判定)。",
      recommendedAction: "当該条件をケース化するか、ケース化できないなら条件そのものを非選択とすることを検討すること。",
    },
    {
      id: "RSC-18",
      nameJa: "選択基準の未宣言",
      severity: "medium",
      definition: "selectionCriteria が1件も宣言されておらず、追加・削減の基準が成果物に残っていない。",
      recommendedAction: "リスク×テストサイズ等、何を軸に残す/落とすかを selectionCriteria に明記すること。",
    },
    {
      id: "RSC-19",
      nameJa: "前バージョン差分の未算出",
      severity: "info",
      definition: "previousSuite が未指定のため、前バージョンとの追加・削除・維持の差分を算出していない。",
      recommendedAction: "前バージョンのスイート構成を previousSuite として渡すと、差分と削除理由の検査まで行える。",
    },
    {
      id: "RSC-20",
      nameJa: "母集団件数の上限超過",
      severity: "info",
      definition: "母集団件数(条件数+ケース数)が maxItems を超えたため、スイート構成・分布・差分の算出を打ち切った。",
      recommendedAction: "対象を絞り込むか、必要であれば maxItems を明示的に引き上げること。",
    },
    {
      id: "RSC-21",
      nameJa: "影響判定実体との申告矛盾（影響あり→影響なし申告）",
      severity: "high",
      definition:
        "影響判定実体(computedImpactVerdicts)で「要修正」または「要再確認」と算出された条件が、changeCategory: existing-unaffected と申告され、影響範囲被覆率の分母から外れている。",
      recommendedAction: "申告を実体に合わせて existing-impacted / modified へ修正し、当該条件をスイート選択の対象に戻すこと。",
    },
    {
      id: "RSC-22",
      nameJa: "影響ありと算出されたケースの非選択",
      severity: "high",
      definition: "影響判定実体で「要修正」または「要再確認」と算出されたテストケースが、スイートに選択(include)されていない。",
      recommendedAction: "当該ケースをスイートへ含めるか、含めない場合は根拠を reason に明記すること。",
    },
    {
      id: "RSC-23",
      nameJa: "影響なしと算出された条件の過大申告",
      severity: "medium",
      definition: "影響判定実体で「影響なし」と算出された条件が modified または existing-impacted と申告されている。",
      recommendedAction: "閾値・パラメータ変更以外の変更要因があるならその根拠を残し、無いなら申告区分を見直すこと。",
    },
    {
      id: "RSC-24",
      nameJa: "影響判定入力の母集団外参照・重複宣言",
      severity: "medium",
      definition:
        "computedImpactVerdicts が母集団に存在しないIDを参照している、または同一項目に対する影響判定が重複宣言されている。",
      recommendedAction: "参照先IDを母集団のIDに合わせ、項目ごとの影響判定を1件に統一すること。",
    },
    {
      id: "RSC-25",
      nameJa: "影響判定実体の未連携",
      severity: "info",
      definition:
        "computedImpactVerdicts が未指定のため、changeCategory 申告の正しさを実体照合しておらず、影響範囲被覆率が申告のみを母集団とした値（basis: declared-only）になっている。",
      recommendedAction: "reexpand_threshold_changes の「成果物別の影響判定」行をそのまま computedImpactVerdicts として渡すこと。",
    },
  ],
  notes: [
    "本検査は渡された母集団に対してのみ成立し、渡していない条件・ケースの取りこぼしは検出できない。",
    "影響範囲被覆率の申告側の分母は changeCategory が new / modified / existing-impacted の条件数であり、分子は選択済みかつ実際にテストケースが存在する条件数である。",
    "推定実行時間は設計時の見積もり値の合計であり、実測値の代替にはしない。一部未申告の場合は下限値として扱う。",
    "削除を禁じる検査ではなく、削除の理由を成果物に残させる検査である。",
    "変更追従(閾値・パラメータ変更に伴う設計の再展開)は reexpand_threshold_changes の担当であり、本ツールは対象外。",
    "影響範囲被覆率の分母は、changeCategory の申告と影響判定実体(computedImpactVerdicts)で影響ありと算出された条件の和集合であり、実体を渡さない場合は申告のみ(basis=declared-only)として扱う。実体照合が裏付けるのは reexpand_threshold_changes が扱う閾値・パラメータ変更に起因する影響のみで、それ以外の変更要因は申告依存のまま残る。",
  ],
};
