import type { TestPlanTemplate } from "../types.js";

// QUINTEE テスト計画書テンプレートの構造データ。
// 章(level 1)17個と、その配下の節(level 2)からなる。
// required は見出し末尾に「*」が付く（必須記入）節を表す。
// isoRef は対応する ISO/IEC/IEEE 29119-3 セクション id（iso29119.ts の id）への対応付け。
// fieldKey は generateTestPlan の入力オブジェクトの対応キー（対応する入力があれば）。
export const testPlanTemplate: TestPlanTemplate = {
  templateName: "QUINTEE テスト計画書テンプレート",
  sections: [
    { id: "introduction", no: "1", titleJa: "はじめに", level: 1, required: false },
    {
      id: "doc-position",
      no: "1.1",
      titleJa: "本ドキュメントの位置づけ",
      level: 2,
      required: true,
      isoRef: "introduction",
      guidance: "本計画書がプロジェクト内で果たす役割・位置づけを記述する。",
    },

    { id: "overview", no: "2", titleJa: "概要", level: 1, required: false },
    {
      id: "scope-target",
      no: "2.1",
      titleJa: "本書の対象",
      level: 2,
      required: true,
      isoRef: "test-items",
      fieldKey: "scope",
      guidance: "本書がカバーするテストの対象範囲の概要を記述する。",
    },
    {
      id: "references-testbase",
      no: "2.2",
      titleJa: "リファレンス（参考資料）およびテストベース",
      level: 2,
      required: true,
      isoRef: "introduction",
      fieldKey: "references",
      guidance: "テスト設計の根拠となる資料（仕様書・要件定義書等）を列挙する。",
    },

    { id: "test-situation", no: "3", titleJa: "テストの状況", level: 1, required: false },
    {
      id: "background",
      no: "3.1",
      titleJa: "テストの背景",
      level: 2,
      required: true,
      isoRef: "introduction",
      fieldKey: "background",
      guidance: "現状の状況やテストに至った背景・懸念を記述する。",
    },
    {
      id: "objectives-goals",
      no: "3.2",
      titleJa: "テストの目的および目標",
      level: 2,
      required: true,
      isoRef: "introduction",
      fieldKey: "objectives",
      guidance: "このテストで達成したい目的と、具体的な目標を記述する。",
    },

    {
      id: "project-position",
      no: "4",
      titleJa: "プロジェクト全体における位置づけ",
      level: 1,
      required: false,
    },
    {
      id: "test-levels",
      no: "4.1",
      titleJa: "対象テストレベル",
      level: 2,
      required: true,
      isoRef: "approach",
      fieldKey: "testLevels",
      guidance: "対象とするテストレベル（単体・結合・システム・受入等）を記述する。",
    },
    {
      id: "project-status",
      no: "4.2",
      titleJa: "プロジェクト全体の状況",
      level: 2,
      required: false,
      guidance: "プロジェクト全体の進行状況・体制上の位置づけを記述する。",
    },
    {
      id: "revision-content",
      no: "4.3",
      titleJa: "具体的な改修内容",
      level: 2,
      required: false,
      fieldKey: "revisionContent",
      guidance: "今回の改修・変更の具体的な内容を記述する。",
    },
    {
      id: "test-items",
      no: "4.4",
      titleJa: "テストアイテム",
      level: 2,
      required: true,
      isoRef: "test-items",
      fieldKey: "testItems",
      guidance: "テスト対象となるアイテム（機能・モジュール等）を列挙する。",
    },
    {
      id: "test-types",
      no: "4.5",
      titleJa: "テストタイプ",
      level: 2,
      required: true,
      isoRef: "approach",
      fieldKey: "selectedTestTypes",
      guidance: "実施するテストタイプを選定する（カタログから対象を選ぶ）。",
    },

    {
      id: "workflow-deliverables",
      no: "5",
      titleJa: "テスト作業全体の流れと成果物",
      level: 1,
      required: false,
      isoRef: "testing-tasks",
      guidance: "テスト作業全体の流れと、各段階での成果物を記述する。",
    },

    { id: "test-scope", no: "6", titleJa: "テストスコープ", level: 1, required: false },
    {
      id: "target-image",
      no: "6.1",
      titleJa: "テスト対象システムイメージ",
      level: 2,
      required: false,
      guidance: "テスト対象システムの全体像・構成イメージを記述する。",
    },
    {
      id: "scope-target-range",
      no: "6.2",
      titleJa: "テスト対象範囲",
      level: 2,
      required: true,
      isoRef: "features-to-be-tested",
      fieldKey: "featuresToTest",
      guidance: "テスト対象とする機能／対象外とする機能を明確にする。",
    },

    { id: "product-risks", no: "7", titleJa: "プロダクトリスク", level: 1, required: false },
    {
      id: "product-risk",
      no: "7.1",
      titleJa: "プロダクトリスク",
      level: 2,
      required: true,
      isoRef: "risks-and-contingencies",
      fieldKey: "risks",
      guidance: "プロダクト品質に関わるリスクと、その影響・対策を記述する。",
    },

    { id: "test-design-policy", no: "8", titleJa: "テスト設計方針", level: 1, required: false },
    {
      id: "viewpoints",
      no: "8.1",
      titleJa: "各機能における観点（大分類／中分類）",
      level: 2,
      required: false,
      guidance: "各機能に対するテスト観点を大分類・中分類で整理する。",
    },
    {
      id: "item-importance",
      no: "8.2",
      titleJa: "テストアイテム別重要度",
      level: 2,
      required: false,
      guidance: "テストアイテムごとの重要度を設定する。",
    },
    {
      id: "viewpoint-importance",
      no: "8.3",
      titleJa: "観点重要度",
      level: 2,
      required: false,
      guidance: "テスト観点ごとの重要度を設定する。",
    },
    {
      id: "feature-importance",
      no: "8.4",
      titleJa: "機能重要度",
      level: 2,
      required: false,
      guidance: "機能ごとの重要度を設定する。",
    },
    {
      id: "test-techniques",
      no: "8.5",
      titleJa: "テストに用いる技法",
      level: 2,
      required: true,
      isoRef: "approach",
      fieldKey: "testTechniques",
      guidance: "テストタイプごとに用いるアプローチ・技法を記述する。",
    },

    { id: "schedule-deliverables", no: "9", titleJa: "スケジュールと成果物", level: 1, required: false },
    {
      id: "test-period",
      no: "9.1",
      titleJa: "テスト期間",
      level: 2,
      required: true,
      isoRef: "schedule",
      fieldKey: "testPeriod",
      guidance: "テスト全体の実施期間を記述する。",
    },
    {
      id: "schedule",
      no: "9.2",
      titleJa: "スケジュール",
      level: 2,
      required: true,
      isoRef: "schedule",
      fieldKey: "scheduleConstraints",
      guidance: "主要な日程・マイルストーンを記述する。",
    },
    {
      id: "deliverables",
      no: "9.3",
      titleJa: "成果物",
      level: 2,
      required: true,
      isoRef: "test-deliverables",
      fieldKey: "deliverables",
      guidance: "テストで作成する成果物を列挙する。",
    },
    {
      id: "estimate",
      no: "9.4",
      titleJa: "見積",
      level: 2,
      required: true,
      guidance: "テスト工数・コストの見積を記述する。",
    },

    {
      id: "judgment-criteria",
      no: "10",
      titleJa: "テスト実施時の各種判定基準",
      level: 1,
      required: false,
    },
    {
      id: "start-end-criteria",
      no: "10.1",
      titleJa: "テスト開始/終了基準",
      level: 2,
      required: true,
      isoRef: "item-pass-fail-criteria",
      fieldKey: "startCriteria",
      guidance: "テストの開始基準と終了基準を記述する。",
    },
    {
      id: "suspension-resumption",
      no: "10.2",
      titleJa: "テスト中断/再開基準",
      level: 2,
      required: true,
      isoRef: "suspension-resumption-criteria",
      fieldKey: "suspensionCriteria",
      guidance: "テストを中断する条件と、再開する条件を記述する。",
    },
    {
      id: "completion-criteria",
      no: "10.3",
      titleJa: "テスト完了基準",
      level: 2,
      required: true,
      isoRef: "item-pass-fail-criteria",
      fieldKey: "completionCriteria",
      guidance: "テストが完了したとみなす基準を記述する。",
    },
    {
      id: "retest-regression",
      no: "10.4",
      titleJa: "再テスト/リグレッションテスト実施条件",
      level: 2,
      required: true,
      guidance: "再テスト・リグレッションテストを実施する条件を記述する。",
    },
    {
      id: "result-judgment",
      no: "10.5",
      titleJa: "テスト実施結果の判定基準",
      level: 2,
      required: true,
      isoRef: "item-pass-fail-criteria",
      fieldKey: "passFailCriteria",
      guidance: "テスト実施結果の判定基準と、判定ステータスの定義を記述する。",
    },
    {
      id: "incident-criteria",
      no: "10.6",
      titleJa: "インシデント判定基準",
      level: 2,
      required: false,
      guidance: "検出したインシデントのランク判定基準を記述する。",
    },
    {
      id: "question-priority",
      no: "10.7",
      titleJa: "質問事項重要度の判定基準",
      level: 2,
      required: false,
      guidance: "質問事項の重要度の判定基準を記述する。",
    },
    {
      id: "execution-record",
      no: "10.8",
      titleJa: "テスト実行時の記録について",
      level: 2,
      required: false,
      guidance: "テスト実行時に記録すべき情報を記述する。",
    },

    { id: "metrics", no: "11", titleJa: "収集するメトリクス", level: 1, required: false },
    {
      id: "collected-metrics",
      no: "11.1",
      titleJa: "収集するメトリクス",
      level: 2,
      required: true,
      fieldKey: "metricsNote",
      guidance: "テスト中に収集・分析するメトリクスを記述する。",
    },

    {
      id: "env-testdata",
      no: "12",
      titleJa: "テスト環境要件およびテストデータ要件",
      level: 1,
      required: false,
    },
    {
      id: "env-requirements",
      no: "12.1",
      titleJa: "テスト環境要件",
      level: 2,
      required: true,
      isoRef: "environmental-needs",
      fieldKey: "environment",
      guidance: "テストに必要な環境（ハード・ソフト・ツール等）を記述する。",
    },
    {
      id: "testdata-requirements",
      no: "12.2",
      titleJa: "テストデータ要件",
      level: 2,
      required: true,
      isoRef: "environmental-needs",
      fieldKey: "testDataRequirements",
      guidance: "テストに必要なデータの要件・準備方針を記述する。",
    },

    {
      id: "communication-org",
      no: "13",
      titleJa: "コミュニケーション・テスト体制",
      level: 1,
      required: false,
    },
    {
      id: "communication",
      no: "13.1",
      titleJa: "コミュニケーション/定期報告方針",
      level: 2,
      required: false,
      guidance: "報告・連絡の方針や定期報告の運用を記述する。",
    },
    {
      id: "incident-flow",
      no: "13.2",
      titleJa: "インシデントの報告および運用の流れ",
      level: 2,
      required: false,
      guidance: "インシデント報告と運用フローを記述する。",
    },
    {
      id: "test-org",
      no: "13.3",
      titleJa: "テスト体制",
      level: 2,
      required: true,
      isoRef: "responsibilities",
      fieldKey: "team",
      guidance: "テスト実施体制（役割・担当）を記述する。",
    },
    {
      id: "test-location",
      no: "13.4",
      titleJa: "テスト作業場所",
      level: 2,
      required: false,
      guidance: "テスト作業を行う場所を記述する。",
    },
    {
      id: "stakeholders",
      no: "13.5",
      titleJa: "ステークホルダー",
      level: 2,
      required: true,
      fieldKey: "stakeholders",
      guidance: "関係するステークホルダーと連絡先を記述する。",
    },
    {
      id: "recruitment",
      no: "13.6",
      titleJa: "採用ニーズ",
      level: 2,
      required: false,
      isoRef: "staffing-and-training-needs",
      guidance: "追加で必要な要員（採用ニーズ）を記述する。",
    },
    {
      id: "training",
      no: "13.7",
      titleJa: "トレーニングの必要性",
      level: 2,
      required: false,
      isoRef: "staffing-and-training-needs",
      guidance: "必要となるトレーニングを記述する。",
    },
    {
      id: "independence",
      no: "13.8",
      titleJa: "テスト実施者の独立性",
      level: 2,
      required: true,
      guidance: "テスト実施者の独立性の確保方針を記述する。",
    },

    {
      id: "foreseeable-risks",
      no: "14",
      titleJa: "予見できるリスクとその対応方針",
      level: 1,
      required: false,
    },
    {
      id: "foreseeable-risk",
      no: "14.1",
      titleJa: "予見できるリスクとその対応方針",
      level: 2,
      required: false,
      guidance: "予見できるリスクと、その対応方針を記述する。",
    },
    {
      id: "project-risk",
      no: "14.2",
      titleJa: "プロジェクトリスク",
      level: 2,
      required: true,
      isoRef: "risks-and-contingencies",
      guidance: "プロジェクト遂行上のリスクと対策を記述する。",
    },

    {
      id: "assumptions-constraints",
      no: "15",
      titleJa: "前提条件と制限事項",
      level: 1,
      required: false,
      fieldKey: "assumptions",
      guidance: "テスト実施の前提条件と制限事項を記述する。",
    },

    { id: "glossary-references", no: "16", titleJa: "用語集および参考文献", level: 1, required: false },
    {
      id: "glossary",
      no: "16.1",
      titleJa: "用語集",
      level: 2,
      required: true,
      fieldKey: "glossary",
      guidance: "本書で用いる用語とその定義を記述する。",
    },
    {
      id: "reference-docs",
      no: "16.2",
      titleJa: "参考文献",
      level: 2,
      required: true,
      fieldKey: "referenceDocs",
      guidance: "参照した文献・資料を列挙する。",
    },

    {
      id: "notes",
      no: "17",
      titleJa: "特記事項",
      level: 1,
      required: false,
      fieldKey: "notes",
      guidance: "その他、特記すべき事項を記述する。",
    },
  ],
};

// --- 固定ボイラープレート（入力に依存せず常に出力する共通リファレンス） ---

// 4.5 テストタイプ・カタログ
export const testTypeCatalog: { name: string; description: string }[] = [
  { name: "機能テスト", description: "機能が期待どおりの結果を返すか確かめる" },
  { name: "シナリオテスト", description: "実際の利用手順に沿って操作し利用できるか確かめる" },
  { name: "性能テスト", description: "処理時間などパフォーマンスを測定" },
  { name: "ロードテスト", description: "様々な状況で動作させ期待どおりか確かめる" },
  { name: "ストレステスト", description: "限界もしくはそれ以上の負荷を与え動作を確かめる" },
  { name: "ユーザビリティテスト", description: "理解されやすく使いやすく魅力的か確かめる" },
  { name: "ローカライゼーションテスト", description: "異なる言語に変換されても機能するか確認" },
  { name: "保守性テスト", description: "欠陥修正や機能追加のしやすさを確かめる" },
  { name: "信頼性テスト", description: "要件で決めた回数・期間・条件で稼働できるか確かめる" },
  { name: "移植性テスト", description: "別ハード・環境への移植のしやすさを確かめる" },
];

// 10.5 判定ステータス定義
export const judgmentStatusDefinitions: { status: string; description: string }[] = [
  { status: "OK", description: "問題なくテストが完了した項目" },
  { status: "NG", description: "インシデントが検出された項目" },
  { status: "QA", description: "QA表で質問中の項目" },
  { status: "NT", description: "テストを実施しない項目（同義：テスト対象外）" },
  {
    status: "N/A",
    description: "テスト実施ができない項目（同義：不可・機能削除・Drop等）",
  },
  {
    status: "保留",
    description: "最終的には実施可能だが現状は何らかの事情で実施できない項目",
  },
];

// 10.6 インシデントランク
export const incidentRankDefinitions: { rank: string; description: string }[] = [
  {
    rank: "ランクA",
    description:
      "基本操作で機能が正常に動作しない／仕様・マニュアルと異なる動作／ユーザーが回避操作不能（フリーズ・リセット等）",
  },
  {
    rank: "ランクB",
    description:
      "ある条件で正常に動作しない／通常想定される性能を大きく下回る／ユーザーが回避操作可能",
  },
  {
    rank: "ランクC",
    description: "特殊条件で機能が正常に動作しない／性能をやや下回る／仕様と区別がつかない",
  },
  { rank: "ランクD", description: "機能・性能・表示系への要望や改良提案" },
];

// 10.7 質問事項重要度
export const questionPriorityDefinitions: { level: string; description: string }[] = [
  { level: "高", description: "テスト続行に支障があり、早急な回答が必要（未回答が●件以上）" },
  { level: "中", description: "テストは続行できるが回答が必要（未回答が○件以上）" },
  { level: "低", description: "確認事項レベルで、続行に支障がない" },
];

// 10.8 テスト実行時の記録
export const executionRecordNotes: string[] = [
  "実行ログとして、実施日・実施者・実行環境・判定結果を記録する。",
  "NG時はインシデントを発行し、管理IDを記録する。",
  "再テストOK時は該当インシデントを更新する。",
];

// 11.1 標準メトリクス
export const standardMetrics: { name: string; items: string }[] = [
  { name: "インシデント曲線", items: "テスト実施日／不具合件数／未解決件数" },
  { name: "インシデント機能別・パレート図", items: "機能別不具合件数／累積割合" },
  { name: "インシデント発生率", items: "テスト項目ごとの実施件数／不具合件数" },
  { name: "不具合検出率", items: "検出済不具合総数／テストケース総数" },
  { name: "不具合収束状況", items: "期間内検出済不具合数／期間内テスト実施時間" },
];
