import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { registerGenerateTestPlanTool } from "./generateTestPlan.js";
import { registerReviewTestPlanTool } from "./reviewTestPlan.js";
import { registerReviseTestPlanTool } from "./reviseTestPlan.js";
import { registerDesignBoundaryValuesTool } from "./designBoundaryValues.js";
import { registerDesignEquivalencePartitioningTool } from "./designEquivalencePartitioning.js";
import { registerReviewTestBasisTool } from "./reviewTestBasis.js";
import { registerAnalyzeRequirementsTool } from "./analyzeRequirements.js";
import { registerExtractTestConditionsTool } from "./extractTestConditions.js";
import { registerGenerateTestCasesTool } from "./generateTestCases.js";
import { registerReviewTestSpecificationTool } from "./reviewTestSpecification.js";
import { registerGenerateExploratoryChartersTool } from "./generateExploratoryCharters.js";
import { registerAuditIdPopulationTool } from "./auditIdPopulation.js";
import { registerGenerateUserStoryMapTool } from "./generateUserStoryMap.js";
import { registerReexpandThresholdChangesTool } from "./reexpandThresholdChanges.js";
import { registerAnalyzeCauseEffectTool } from "./analyzeCauseEffect.js";
import { registerDesignDecisionTableTool } from "./designDecisionTable.js";
import { registerDesignPairwiseTool } from "./designPairwise.js";
import { registerDesignConfigMatrixTool } from "./designConfigMatrix.js";
import { registerDesignScenarioFlowsTool } from "./designScenarioFlows.js";
import { registerDesignTestArchitectureTool } from "./designTestArchitecture.js";
import { registerDesignTestDataTool } from "./designTestData.js";
import { registerAuditCrossMatrixTool } from "./auditCrossMatrix.js";
import { registerAuditBasisContradictionsTool } from "./auditBasisContradictions.js";
import { registerGenerateBusinessRequirementModelTool } from "./generateBusinessRequirementModel.js";
import { registerSelectRegressionSuiteTool } from "./selectRegressionSuite.js";

export function registerTools(server: McpServer): void {
  registerGenerateTestPlanTool(server);
  registerReviewTestPlanTool(server);
  registerReviseTestPlanTool(server);
  registerDesignBoundaryValuesTool(server);
  registerDesignEquivalencePartitioningTool(server);
  registerReviewTestBasisTool(server);
  registerAnalyzeRequirementsTool(server);
  registerExtractTestConditionsTool(server);
  registerGenerateTestCasesTool(server);
  registerReviewTestSpecificationTool(server);
  registerGenerateExploratoryChartersTool(server);
  registerAuditIdPopulationTool(server);
  registerGenerateUserStoryMapTool(server);
  registerReexpandThresholdChangesTool(server);
  registerAnalyzeCauseEffectTool(server);
  registerDesignDecisionTableTool(server);
  registerDesignPairwiseTool(server);
  registerDesignConfigMatrixTool(server);
  registerDesignScenarioFlowsTool(server);
  registerDesignTestArchitectureTool(server);
  registerDesignTestDataTool(server);
  registerAuditCrossMatrixTool(server);
  registerAuditBasisContradictionsTool(server);
  registerGenerateBusinessRequirementModelTool(server);
  registerSelectRegressionSuiteTool(server);
}
